# syntax=docker/dockerfile:1

# --- Base Stage ---
FROM python:3.10-slim as base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    tini \
    # required for psycopg2
    libpq-dev \
    # WeasyPrint dependencies
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf-2.0-0 \
    shared-mime-info \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libexif-dev \
    libgobject-2.0-0 \
    libffi-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-tools \
    gstreamer1.0-x \
    # other dependencies
    nmap \
    # cleanup
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# --- Builder Stage ---
FROM base as builder

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    libpcap-dev \
    # cleanup
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Go
ARG GOVERSION=1.21.5
RUN curl -s -L -o /tmp/go.tar.gz https://go.dev/dl/go${GOVERSION}.linux-amd64.tar.gz \
    && tar -xzC /usr/local -f /tmp/go.tar.gz \
    && rm /tmp/go.tar.gz
ENV GOROOT="/usr/local/go"
ENV GOPATH=$HOME/go
ENV PATH="${PATH}:${GOROOT}/bin:${GOPATH}/bin"

# Install Go packages
WORKDIR /usr/src/app
ENV GO111MODULE=on
RUN set -eux; \
    go install github.com/jaeles-project/gospider@latest; \
    go install github.com/tomnomnom/gf@latest; \
    go install github.com/tomnomnom/unfurl@latest; \
    go install github.com/tomnomnom/waybackurls@latest; \
    go install github.com/projectdiscovery/httpx/cmd/httpx@latest; \
    go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest; \
    go install github.com/projectdiscovery/chaos-client/cmd/chaos@latest; \
    go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest; \
    go install github.com/projectdiscovery/naabu/v2/cmd/naabu@latest; \
    go install github.com/hakluke/hakrawler@latest; \
    go install github.com/lc/gau/v2/cmd/gau@latest; \
    go install github.com/owasp-amass/amass/v3/...; \
    go install github.com/ffuf/ffuf@latest; \
    go install github.com/projectdiscovery/tlsx/cmd/tlsx@latest; \
    go install github.com/hahwul/dalfox/v2@latest; \
    go install github.com/projectdiscovery/katana/cmd/katana@latest; \
    go install github.com/dwisiswant0/crlfuzz/cmd/crlfuzz@latest; \
    go install github.com/sa7mon/s3scanner@latest; \
    rm -rf /go/pkg/* && rm -rf /root/.cache/go-build

# --- Final Stage ---
FROM base as final

LABEL \
    name="reconPoint" \
    author="KhulnaSoft Ltd <security@khulnasoft.com>" \
    description="reconPoint is a automated pipeline of recon process, useful for information gathering during web application penetration testing."

WORKDIR /usr/src/app

# Copy Go binaries from builder
COPY --from=builder /go/bin/* /usr/local/bin/

# Copy requirements
COPY ./requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

COPY . .

ENTRYPOINT ["/usr/bin/tini", "--"]
